PACKAGE_NAME="ce100g2-switch"
PACKAGE_VERSION="0.1.10"
BUILT_MODULE_NAME[0]="ce100g2_switch"
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_NAME[1]="ixgbe"
BUILT_MODULE_LOCATION[1]="ixgbe"
DEST_MODULE_LOCATION[1]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
